services:
  - type: web
    name: algoritimo-trade
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python dashboard/app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PORT
        value: 5000


